stages:
  - build
  - test

variables:
  NODE_VERSION: "18"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"

default:
  image: node:$NODE_VERSION

cache:
  paths:
    - node_modules/
    - .npm

before_script:
  - npm ci --legacy-peer-deps

build:
  stage: build
  script:
    - echo Build job started
    - echo ls -l
    - ls -l
    - npm run build
    - echo ls -l build
    - ls -l build
    - echo Build job completed
  artifacts:
    paths:
      - build/
  only:
    - master
  tags:
    - itmolabs

test:
  stage: test
  script:
    - echo Test job started
    - npm run test --watchAll=false
    - echo Test job completed
  only:
    - master
  tags:
    - itmolabs
