export const SIGN_IN = 'AUTH/SIGN_IN';
export const SIGN_OUT = 'AUTH/SIGN_OUT';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const UPDATE_USER_REVIEWS = 'ORDER/UPDATE_USER_REVIEWS';
export const UPDATE_APPROVED_REVIEWS = 'ORDER/UPDATE_APPROVED_REVIEWS';
export const UPDATE_NOT_APPROVED_REVIEWS = 'ORDER/UPDATE_NOT_APPROVED_REVIEWS';